import = [
  "~/.config/alacritty/themes/dracula.toml",
]

[font]
size = 11

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "IBM Plex Mono"

[scrolling]
history = 100000
